spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS}
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:expo}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:12345}
  jpa:
    hibernate:
      dialect: ${DB_DIALECT}
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: true

jwt:
  accessSecret: ${JWT_ACCESS_SECRET}
  refreshSecret: ${JWT_REFRESH_SECRET}

sms:
  apiKey: ${SMS_API_KEY}
  apiSecret: ${SMS_API_SECRET}
  fromnumber: ${SMS_FROM_NUMBER}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_STATIC}
    s3:
      image-bucket: ${AWS_S3_IMAGE_BUCKET}
      qr-bucket: ${AWS_S3_QR_BUCKET}
    stack:
      auto: false

discord:
  errorUrl: ${DISCORD_ERROR_URL}
  participantNumberUrl: ${DISCORD_PARTICIPANT_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"