spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS}
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      dialect: ${DB_DIALECT}
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  accessSecret: ${JWT_ACCESS_SECRET}
  refreshSecret: ${JWT_REFRESH_SECRET}

sms:
  apiKey: ${SMS_API_KEY}
  apiSecret: ${SMS_API_SECRET}
  fromnumber: ${SMS_FROM_NUMBER}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_STATIC}
    s3:
      bucket: ${AWS_S3_BUCKET}
    stack:
      auto: false

discord:
  errorUrl: ${DISCORD_ERROR_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"